ejemplo1:
	gcc -c ejemplo1.c generacion.c generacion.h
	gcc -o ejemplo1 ejemplo1.c generacion.c generacion.h -lm
	./ejemplo1 ejemplo1.asm
	nasm -g -o ejemplo1.o -f elf32 ejemplo1.asm
	gcc -m32 -o ejemplo1 ejemplo1.o alfalib.o

ejemplo2:
	gcc -c ejemplo2.c generacion.c generacion.h
	gcc -o ejemplo2 ejemplo2.c generacion.c generacion.h -lm
	./ejemplo2 ejemplo2.asm
	nasm -g -o ejemplo2.o -f elf32 ejemplo2.asm
	gcc -m32 -o ejemplo2 ejemplo2.o alfalib.o

ejemplo3:
	gcc -c ejemplo3.c generacion.c generacion.h
	gcc -o ejemplo3 ejemplo3.c generacion.c generacion.h -lm
	./ejemplo3 ejemplo3.asm
	nasm -g -o ejemplo3.o -f elf32 ejemplo3.asm
	gcc -m32 -o ejemplo3 ejemplo3.o alfalib.o

ejemplo4:
	gcc -c ejemplo4.c generacion.c generacion.h
	gcc -o ejemplo4 ejemplo4.c generacion.c generacion.h -lm
	./ejemplo4 ejemplo4.asm
	nasm -g -o ejemplo4.o -f elf32 ejemplo4.asm
	gcc -m32 -o ejemplo4 ejemplo4.o alfalib.o

ejemplo5:
	gcc -c ejemplo5.c generacion.c generacion.h
	gcc -o ejemplo5 ejemplo5.c generacion.c generacion.h -lm
	./ejemplo5 ejemplo5.asm
	nasm -g -o ejemplo5.o -f elf32 ejemplo5.asm
	gcc -m32 -o ejemplo5 ejemplo5.o alfalib.o


ejemplo6:
	gcc -c ejemplo6.c generacion.c generacion.h
	gcc -o ejemplo6 ejemplo6.c generacion.c generacion.h -lm
	./ejemplo6 ejemplo6.asm
	nasm -g -o ejemplo6.o -f elf32 ejemplo6.asm
	gcc -m32 -o ejemplo6 ejemplo6.o alfalib.o

ejemplo7:
	gcc -c ejemplo7.c generacion.c generacion.h
	gcc -o ejemplo7 ejemplo7.c generacion.c generacion.h -lm
	./ejemplo7 ejemplo7.asm
	nasm -g -o ejemplo7.o -f elf32 ejemplo7.asm
	gcc -m32 -o ejemplo7 ejemplo7.o alfalib.o

clean:
	rm -r ejemplo5.asm ejemplo5 generacion.h.gch generacion.o ejemplo5.o ejemplo4.asm ejemplo4 ejemplo4.o ejemplo6.asm ejemplo6 ejemplo6.o ejemplo1.asm ejemplo1 ejemplo1.o ejemplo2.asm ejemplo2 ejemplo2.o ejemplo3.asm ejemplo3 ejemplo3.o ejemplo7.asm ejemplo7 ejemplo7.o
